# Generated by Django 2.2.24 on 2022-02-12 15:23

from django.db import migrations
from phonenumbers import is_valid_number, parse, NumberParseException


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            pure_phonenumber = parse(flat.owners_phonenumber, 'RU')
        except NumberParseException:
            break
        if is_valid_number(pure_phonenumber):
            flat.owner_pure_phone = pure_phonenumber
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0006_auto_20220212_1821'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone, move_backward)
    ]
