# Generated by Django 2.2.24 on 2022-02-12 16:25

from django.db import migrations


def fill_owner_model(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            owner=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            defaults={'owners_phonenumber': flat.owners_phonenumber}
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owner_model)
    ]
